### ISSUE TITLE
Default resolution for remote screen

### ISSUE THREAD

**Issue by oasis1234** [dchapyshev/aspia#154]
Is there any config/setting/param to set the initial resolution of the remote screen.
Aspia always connects using 1024x768 but I want to use 1280x960.
I've been looking at the source code (\source\client\ui\client_settings.cc, \source\console\settings.cc) but that's beyond my knowledge.
Thank you.
I'm an old Radmin user and, since I discovered this wonderful Aspia, I will never go back.

**Comment by dchapyshev** [comment]
It can't be done. Before connecting, it is not known what resolutions your video adapter and specific physical monitor support.

**Comment by oasis1234** [comment]
![home-alone](https://user-images.githubusercontent.com/16627030/164091173-78d9ccd6-ce2a-432d-8a4c-8c41312d9a3f.jpg)
You replied in less than 5 minutes!

**Comment by dchapyshev** [comment]
I always read if someone writes. If I did not answer immediately, this means that I have read the information and taken note of it and when there is a result - I will definitely answer.
In this case, I answered because it is impossible to do well what you ask.
If you don't mind, I'll close the issue. If you have an opposite opinion, then you can open it again and justify your opinion.

**Comment by oasis1234** [comment]
Finally I found the solution. Just a little contribution to the community, in case someone is reading this.

Changing the resolution using Aspia's button "Resolution selection" changes the screen resolution just temporarily. It will be reset on next connection.
The "default" resolution is set using Windows option. Settings > Display > Resolution. **That resolution will remain**.
I was going mad because I had to change the resolution on every connection.
