### ISSUE TITLE
How to use mirror driver?

### ISSUE THREAD

**Issue by lvshiling** [dchapyshev/aspia#3]

**Comment by dchapyshev** [comment]
Work with mirror driver is not implemented in the program at this time. I do not have a digital signature for drivers. Without a digital signature, the driver can not be loaded into Windows Vista/7/8/10.

**Comment by denadmin** [comment]
no need to use externtal mirror driver for windows since 8
check out **Desktop Duplication API**

**Comment by dchapyshev** [comment]
Desktop Duplication API works since Windows 8. I support Windows XP SP3/Vista/7. I planned to use the Desktop Duplication API for new systems and the mirror driver for older systems.
These are plans for the future. Now I'm busy supporting a session of system information (like AIDA64, but for working through the network).
