### ISSUE TITLE
BOOL LookupPrivilegeValueW(LPCWSTR,LPCWSTR,PLUID)

### ISSUE THREAD

**Issue by lostStara** [dchapyshev/aspia#63]
C:\aspia-1.1.0\source\base\win\process_util.cc(146): error C2664: “BOOL LookupPrivilegeValueW(LPCWSTR,LPCWSTR,PLUID)”: Unable to set parameters 2 “const char [15]”convert“LPCWSTR”

**Comment by dchapyshev** [comment]
All the problems that you wrote (#63, #64, #65, #66, #67) because you did not read the [building instructions](https://github.com/dchapyshev/aspia/blob/master/doc/building.md) or do not comply with them.
None of the above problems exist, this is confirmed by the automatic build, tests and user-running application.

**Comment by dchapyshev** [comment]
Your bug report should match one of the templates that are offered during creation (Bug report, Feature request).
Now your reports do not contain any useful information.
The issue will be closed. Create a new issue in accordance with the rules of the project.
